[project]
name = "jacobi-takehome-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.6",
    "ultralytics>=8.3.126",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
